<a href="https://colab.research.google.com/github/hritikchaturvedi11/Diabetes-Prediction/blob/main/Diabetes_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# Data Preprocessing

In [2]:
# loading the dataset

diabetes_dataset = pd.read_csv('/content/drive/MyDrive/Diabates prediction/Dataset/diabetes.csv')

In [3]:
diabetes_dataset.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [4]:
diabetes_dataset.shape

(768, 9)

In [5]:
diabetes_dataset.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [6]:
diabetes_dataset['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

### 0 --> Non - diabetic
### 1 --> Diabetic

In [7]:
diabetes_dataset.groupby('Outcome').mean()

Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...                                     
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

In [8]:
x = diabetes_dataset.drop(columns = 'Outcome')
x

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [10]:
y = diabetes_dataset['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

# Data Standardization

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
standardized_data = scaler.transform(x)

In [16]:
X = standardized_data
Y = diabetes_dataset['Outcome']

In [17]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [18]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

# Test Train Split

In [19]:
X_train, X_test,Y_train,Y_test = train_test_split(X,Y, test_size = 0.2, stratify = Y, random_state = 2)             

# Training a model

In [20]:
classifier = svm.SVC(kernel='linear')

In [22]:
# Training the support vector machine classifier
classifier.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

# Model Evaluation

## Model Accuracy

### Train data accuracy

In [25]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [26]:
training_data_accuracy

0.7866449511400652

### Test data accuracy

In [27]:
X_test_prediction = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [28]:
testing_data_accuracy

0.7727272727272727

# Making a predictive system


In [40]:
input_data = (3.298000,	109.980000,	68.184000,	19.664000,	68.792000,	30.304200,	0.429734,	31.190000)

# Changing the input data to numpy array

input_data_as_numpy_array = np.asarray(input_data)
input_data_as_numpy_array

array([  3.298   , 109.98    ,  68.184   ,  19.664   ,  68.792   ,
        30.3042  ,   0.429734,  31.19    ])

In [41]:
# reshape the array
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)


In [42]:
# standardize the input data
std_data = scaler.transform(input_data_reshape)
std_data

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
# Prediction
prediction = classifier.predict(std_data)

In [44]:
prediction

array([0])

In [46]:
if prediction[0] == 0:
  print('Person is not diabetic')
else:
  print('Person is a diabetic')


Person is not diabetic
